# Generated by Django 2.2.6 on 2019-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('recipient_name', models.CharField(max_length=30)),
                ('post_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
