# Generated by Django 2.2.6 on 2019-10-29 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField(default=0)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('transaction_accepted', models.BooleanField(default=False)),
                ('transaction_money_add', models.BooleanField(default=False)),
                ('transaction_group', models.BooleanField(default=False)),
                ('transaction_user_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('transaction_user_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
